"""Update model for GenevaEducation table

Revision ID: 4cd95d233fc5
Revises: 8a399ba48e3a
Create Date: 2026-07-14 11:15:44.607129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cd95d233fc5'
down_revision = '8a399ba48e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni_geneva_educations', schema=None) as batch_op:
        batch_op.drop_column('degree')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni_geneva_educations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('degree', mysql.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###
