"""Add nameplate field

Revision ID: 8a399ba48e3a
Revises: d3e4f482ef9c
Create Date: 2026-07-14 06:56:10.870473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a399ba48e3a'
down_revision = 'd3e4f482ef9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni_class_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nameplate', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni_class_notes', schema=None) as batch_op:
        batch_op.drop_column('nameplate')

    # ### end Alembic commands ###
