"""Initial alumni schema

Revision ID: 94a247e9ee6c
Revises: 
Create Date: 2026-06-25 11:31:23.995120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a247e9ee6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('maiden_name', sa.String(length=100), nullable=True),
    sa.Column('pref_salutation', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('phone_type', sa.Enum('MOBILE', 'HOME', name='phonetype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumni_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumnus_id', sa.Integer(), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['alumnus_id'], ['alumni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumni_geneva_educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumnus_id', sa.Integer(), nullable=False),
    sa.Column('degree_level', sa.String(length=50), nullable=True),
    sa.Column('degree', sa.String(length=150), nullable=True),
    sa.Column('graduation_year', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['alumnus_id'], ['alumni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumni_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumnus_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_types', sa.JSON(), nullable=True),
    sa.Column('wants_class_note', sa.Boolean(), nullable=True),
    sa.Column('additional_updates', sa.Text(), nullable=True),
    sa.Column('volunteer_radio', sa.Boolean(), nullable=True),
    sa.Column('volunteer_choices', sa.JSON(), nullable=True),
    sa.Column('other_volunteer', sa.Text(), nullable=True),
    sa.Column('viewed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['alumnus_id'], ['alumni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumni_children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumni_update_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['alumni_update_id'], ['alumni_updates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumni_class_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumni_update_id', sa.Integer(), nullable=False),
    sa.Column('class_note_text', sa.Text(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alumni_update_id'], ['alumni_updates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumni_update_id')
    )
    op.create_table('alumni_education_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumni_update_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=150), nullable=True),
    sa.Column('degree', sa.String(length=150), nullable=True),
    sa.Column('graduation_year', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['alumni_update_id'], ['alumni_updates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumni_employment_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumni_update_id', sa.Integer(), nullable=False),
    sa.Column('employer', sa.String(length=150), nullable=True),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['alumni_update_id'], ['alumni_updates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumni_family_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumni_update_id', sa.Integer(), nullable=False),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('spouse_name', sa.String(length=150), nullable=True),
    sa.Column('is_spouse_geneva_grad', sa.Boolean(), nullable=True),
    sa.Column('spouse_geneva_degrees', sa.JSON(), nullable=True),
    sa.Column('spouse_undergrad_year', sa.String(length=4), nullable=True),
    sa.Column('spouse_graduate_year', sa.String(length=4), nullable=True),
    sa.Column('spouse_online_year', sa.String(length=4), nullable=True),
    sa.Column('marry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['alumni_update_id'], ['alumni_updates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumni_update_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumni_family_updates')
    op.drop_table('alumni_employment_updates')
    op.drop_table('alumni_education_updates')
    op.drop_table('alumni_class_notes')
    op.drop_table('alumni_children')
    op.drop_table('alumni_updates')
    op.drop_table('alumni_geneva_educations')
    op.drop_table('alumni_addresses')
    op.drop_table('alumni')
    # ### end Alembic commands ###
