"""Update volunteer form, remove radio button option

Revision ID: d3e4f482ef9c
Revises: fc991cf31df4
Create Date: 2026-07-08 14:35:33.205372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3e4f482ef9c'
down_revision = 'fc991cf31df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni_updates', schema=None) as batch_op:
        batch_op.drop_column('volunteer_radio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volunteer_radio', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
